version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pawfinders-network

  app:
    build: .  # Correct indentation
    image: s224719679/keerthanapawfinders:latest
    container_name: pawfinders-app
    environment:
      - MONGODB_URI = 'mongodb+srv://keerthuvije:ZEZS1JlZIvPPwkPe@cluster0.avmbigb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
    ports:
      - "3041:3041"
    depends_on:
      - mongo
    networks:
      - pawfinders-network
    volumes:
      - .:/usr/src/app

volumes:
  mongo-data:

networks:
  pawfinders-network:
    driver: bridge
